/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'dataDelivery' : IDL.Text,
  'projectName' : IDL.Text,
  'qnrName' : IDL.Text,
  'projectLaunchDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'receivedDate' : IDL.Text,
  'quotaRedirectStatus' : IDL.Text,
  'linkStatus' : IDL.Text,
  'dataStatus' : IDL.Text,
});
export const EditEntry = IDL.Record({
  'id' : IDL.Nat,
  'oldValue' : IDL.Text,
  'newValue' : IDL.Text,
  'projectId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'fieldName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProject' : IDL.Func([Project], [IDL.Nat], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getEditHistory' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(EditEntry)],
      ['query'],
    ),
  'getProjectEditHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EditEntry)],
      ['query'],
    ),
  'getProjectsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'updateProjectField' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'dataDelivery' : IDL.Text,
    'projectName' : IDL.Text,
    'qnrName' : IDL.Text,
    'projectLaunchDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'receivedDate' : IDL.Text,
    'quotaRedirectStatus' : IDL.Text,
    'linkStatus' : IDL.Text,
    'dataStatus' : IDL.Text,
  });
  const EditEntry = IDL.Record({
    'id' : IDL.Nat,
    'oldValue' : IDL.Text,
    'newValue' : IDL.Text,
    'projectId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'fieldName' : IDL.Text,
  });
  
  return IDL.Service({
    'addProject' : IDL.Func([Project], [IDL.Nat], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getEditHistory' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(EditEntry)],
        ['query'],
      ),
    'getProjectEditHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EditEntry)],
        ['query'],
      ),
    'getProjectsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'updateProjectField' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };