/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EditEntry {
  'id' : bigint,
  'oldValue' : string,
  'newValue' : string,
  'projectId' : bigint,
  'timestamp' : bigint,
  'fieldName' : string,
}
export interface Project {
  'id' : bigint,
  'region' : string,
  'dataDelivery' : string,
  'projectName' : string,
  'qnrName' : string,
  'projectLaunchDate' : string,
  'createdAt' : bigint,
  'receivedDate' : string,
  'quotaRedirectStatus' : string,
  'linkStatus' : string,
  'dataStatus' : string,
}
export interface _SERVICE {
  'addProject' : ActorMethod<[Project], bigint>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getEditHistory' : ActorMethod<[bigint, string], Array<EditEntry>>,
  'getProjectEditHistory' : ActorMethod<[bigint], Array<EditEntry>>,
  'getProjectsByRegion' : ActorMethod<[string], Array<Project>>,
  'updateProjectField' : ActorMethod<[bigint, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];